---
- name: Importar de role common
  ansible.builtin.import_tasks: hola.yml

- name: Mensaje pera
  ansible.builtin.import_tasks: pera.yml

- name: Importar de role common
  ansible.builtin.import_tasks: manzana.yml
