---
- name: do something
  include_role:
    name: common
    tasks_from: hola
  vars:
    nombre: "Ari"

- name: Mensaje pera
  ansible.builtin.import_tasks: pera.yml

- name: do something
  include_role:
    name: common
    tasks_from: manzana
