---
- name: Block for RC
  hosts: masterbp.corp.daytwo.cloud
  gather_facts: false
  tasks:
  - name: block for RC
    include_tasks: block_task.yml
    loop: "{{ lookup('ansible.builtin.dict', servers) | list }}"

  - name: creacion file
    ansible.builtin.command: 'echo "hola mundo" > /tmp/ari_prueba.txt'
   
  - name: prueba until
    ansible.builtin.command: cat /tmp/ari_prueba.txt
    register: stop_service_result
    until: "'ADMU4000I' in stop_service_result['stdout']"
    retries: 20
    delay: 30

  - name: prueba until 2
    ansible.builtin.shell: 'cat /tmp/ari_prueba.txt | wc -l' 
    register: line_count
    until: line_count == '9'
    retries: 20
    delay: 30


