- name: echo
  ansible.builtin.command: echo {{ item.value }}
  register: server_list
    
- name: print server_list
  debug:
    msg: "El RC no es igual a 0. Es {{ server_list.results.rc }}"
  when: server_list.results.rc != 0

- name: print server_list
  debug:
    msg: "El RC es igual a 0"
  when: server_list.results.rc == 0
