---
- name: Block for RC
  hosts: masterbp.corp.daytwo.cloud
  gather_facts: false
  vars:
  - number: Mundo
  tasks:
  - name: block for RC
    include_tasks: block_task.yml
    loop: "{{ lookup('ansible.builtin.dict', servers) | list }}"

  - name: creacion file
    ansible.builtin.command: 'echo "hola mundo" > /tmp/ari_prueba.txt'
   
  - name: prueba until
    ansible.builtin.command: cat /tmp/ari_prueba.txt
    register: stop_service_result
    until: "'ADMU4000I' in stop_service_result['stdout']"
    retries: 20
    delay: 30

  - name: prueba until 2
    ansible.builtin.shell: 'echo ${number}' 
    register: output_ari

  - name: prueba until 2
    ansible.builtin.shell: 'echo {{ number }}' 

  - debug:
      msg: "{{ output_ari }}"

  - name: print var 1
    ansible.builtin.command: '"{{ password_test }}" > /tmp/ari_prueba.txt'

  - name: print var 2
    ansible.builtin.command: '${password_test_2} > /tmp/ari_prueba.txt'
    environment:
      password_test_2: "{{ password_test }}"
