- name: echo
  ansible.builtin.command: echo {{ item.value }}
  register: server_list
    
- name: print server_list
  debug:
    msg: "El RC del stop del servicio en {{ item.value }} no es igual a 0. Es {{ server_list.results.rc }}"
  when: server_list.rc != 0

- name: print server_list
  debug:
    msg: "El RC del stop del servicio en {{ item.value }} es igual a 0"
  when: server_list.rc == 0
