---
- name: Block for RC
  hosts: master
  gather_facts: false
  tasks:
  - name: block for RC
    include_tasks: block_task.yml
    loop: "{{ lookup('ansible.builtin.dict', servers) | list }}"

  - name: prueba until
    ansible.builtin.command: echo "hola mundo" > /tmp/ari_prueba.txt
    register: stop_service_result
    changed_when: true
    until: "'ADMU4000I' in stop_service_result['stdout']"
    retries: 20
    delay: 30


