---
- name: "USER on AIX"
  hosts: all
  become: false
  gather_facts: true
  collections: 
  - ibm.power_aix
  tasks:
  - name: "Create user"
    ibm.power_aix.user:
      state: present
      name: ari
      change_passwd_on_login: False
      password: 12345
      attributes:
        home: /home/student
        data: 902
