---
- name: test
  hosts: all
  gather_facts: true
  collections:
  - community.windows
  tasks:
  - name: Unzip a bz2 (BZip) file
    community.windows.win_unzip:
      src: C:\Users\Phil\Logs.bz2
      dest: C:\Users\Phil\OldLogs
      creates: C:\Users\Phil\OldLogs
