---
- name: "USER on AIX"
  hosts: all
  become: false
  gather_facts: true
  vars:
    ansible_connection: network_cli
  collections: 
  - ibm.power_aix
  tasks:
  - name: Mount filesystems
    ibm.power_aix.mount:
      state: mount
      mount_dir: /mnt/tesfs
