---
- name: Selinux State
  hosts: all
  become: true
  vars_files:
    - "./vars/main.yml"
  tasks:

  - name: Get Selinux
    ansible.builtin.command: getenforce
    register: selinux_state

  - name: Set Fact
    ansible.builtin.set_fact: selinux_state="{{ selinux_state.stdout }}"

  - name: Print Selinux
    ansible.builtin.debug:
      msg: "{{ ansible_hostname }} {{ selinux_state }}"

  - name: Print nombre
    ansible.builtin.debug:
      msg: "{{ servicio }}"

  - name: Print nombre_prueba
    ansible.builtin.debug:
      msg: "{{ item.nombre_prueba }}"
    loop: '{{ vars[servicio] }}'

  - name: Print nombre_prueba
    ansible.builtin.command: echo "{{ item.nombre_prueba }}"
    loop: '{{ vars[servicio] }}'
    register: resultado

  - name: Print nombre_prueba
    ansible.builtin.set_fact:
      resultado_sesion: "'{{ resultado.results | map(attribute='stdout') | string }}'"

  - name: Print nombre_prueba
    ansible.builtin.debug:
      msg: "{{ resultado_sesion }}"


      

