---
- name: Selinux State
  hosts: all
  tasks:

  - name: Get Selinux
    ansible.builtin.command: getenforce
    register: selinux_state

  - name: Print Selinux
    debug:
      msg: "{{ ansible_hostname }} {{ selinux_state }}"

