---
- name: Selinux State
  hosts: all
  become: true
  tasks:

  - name: Get Selinux
    ansible.builtin.command: getenforce
    register: selinux_state

  - name: Set Fact
    ansible.builtin.set_fact: selinux_state="{{ selinux_state.stdout }}"

  - name: Print Selinux
    ansible.builtin.debug:
      msg: "{{ ansible_hostname }} {{ selinux_state }}"


      

