---
- name: Selinux State
  hosts: all
  tasks:

  - name: Get Selinux
    ansible.builtin.command: getenforce
    register: selinux_state

  - name: Get Selinux
    ansible.builtin.set_fact: selinux_state="{{ selinux_state.result }}"

  - name: Print Selinux
    debug:
      msg: "{{ ansible_hostname }} {{ selinux_state }}"

- name: Selinux State
  hosts: localhost
  tasks:
  
  - name: Template a file 
    ansible.builtin.template:
      src: selinux.j2
      dest: /tmp/selinux.txt



      

