---
- name: "Banco Pichincha ::: Start Services WAS Omnicanal ::: Playbook para subir servicios de capa media WAS Omnicanal"
  hosts: all
  gather_facts: false
  tasks:

  - name: "Banco Pichincha ::: Start Services WAS Omnicanal ::: Inicia servicios"
    ansible.builtin.command: echo {{ item.value }}
    register: server_list
    loop: "{{ lookup('ansible.builtin.dict', servers) | list }}"

  - name: print server_list
    debug:
      msg: "{{ server_list }}"

  - name: Se declara lista
    set_fact:
      RCS: "{{ server_list | json_query(query) | list }}"
    vars:
      query: 'results[].rc'

  - name: Imprime namespaces con loop
    debug:
      msg: "{{ item }}"
    loop: "{{ RCS }}"
      
