---
- name: Intro to Ansible Playbooks
  hosts: all

  tasks:
  - name: print message
    debug:
      msg: "HELLO"
  - name: Create user aixguest1010
    ibm.power_aix.user:
      state: present
      name: aixguest1010
      change_passwd_on_login: False
      password: as$12ndhkfjk$1c
      attributes:
        home: /home/test/aixguest1010
        data: 1272
